[package]
name = "deadbear_fib_rs"
version = "0.1.0"
authors = ["Sean Baier<sean.baier@deadbear.io>"]
edition = "2018"

[dependencies]

[dependencies.pyo3]
version = "0.16.6"
features = ["extension-module"]


[lib]
name = "deadbear_fib_rs"
crate-type = ["cdylib"]